apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-hosting

helmCharts:
- name: vllm-kserve
  releaseName: llama-32-1b-instruct-cpu
  version: 0.5.9
  repo: https://redhat-ai-services.github.io/helm-charts/
  valuesFile: values.yaml
